# Generated by Django 4.2.5 on 2023-09-28 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExtractedData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.CharField(max_length=200)),
                ("end_date", models.CharField(max_length=200)),
                (
                    "min_contribution",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "max_contribution",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
            ],
        ),
    ]
